%YAML:1.0

camera:
  fx: 320.0
  fy: 320.0
  cx: 320.0
  cy: 240.0

detector:
  type: SuperPoint

matcher:
  type: LightGlue

bucketing:
  enabled: 1
  grid_cols: 6
  grid_rows: 3
  max_features_per_bucket: 70

local_bundle_adjustment:
  enabled: 0
  window_size: 10

system:
  backend: CUDA
  num_threads: 12
  verbose: 0

airsim:
  playback_velocity: 3.0
