%YAML:1.0

dataset:
  root_path: ../../../VO-datasets/KITTI/data_odometry_gray/dataset
  sequence: '00'

detector:
  type: SIFT
  SIFT:
    nfeatures: 1000
    nOctaveLayers: 3
    contrastThreshold: 0.04
    edgeThreshold: 10
    sigma: 1.6

matcher:
  type: Kinematic
  distance_ratio: 0.75
  
bucketing:
  enabled: 1
  grid_cols: 6
  grid_rows: 3
  max_features_per_bucket: 70
 
local_bundle_adjustment:
  enabled: 0
  window_size: 10 

system:
  backend: CUDA
  num_threads: 12
  verbose: 0
